### ISSUE TITLE
PDF fails to open if special character in path

### ISSUE THREAD

**Issue by oliviercailloux** [metachris/pdfx#23]
$ pdfx Prés/presentation.pdf 
Traceback (most recent call last):
  File "/usr/local/bin/pdfx", line 9, in <module>
    load_entry_point('pdfx==1.3.0', 'console_scripts', 'pdfx')()
  File "build/bdist.linux-x86_64/egg/pdfx/cli.py", line 149, in main
  File "build/bdist.linux-x86_64/egg/pdfx/__init__.py", line 99, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)

But the PDF opens fine with;:
$ cd Prés
$ pdfx presentation.pdf

**Comment by metachris** [comment]
Should be fixed now. Please let me know if it still persists with v1.4.1
